using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShootBullet : MonoBehaviour
{
    [SerializeField] private GameObject bulletPrefab;
    [SerializeField] private float throwForce = 700f;


    private void Update()
    {
        if(Input.GetMouseButtonDown(0))
        {
            Shoot();
        }
    }

    private void Shoot()
    {

        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);

        GameObject bullet = Instantiate(bulletPrefab, Camera.main.transform.position, Quaternion.identity);
        Rigidbody rb = bullet.GetComponent<Rigidbody>();

        Vector3 forceDirection = ray.direction;

        rb.AddForce(forceDirection * throwForce);

        Destroy(bullet, 5);
    }

}
